# Generated by Django 4.2.30 on 2026-04-27 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repofile',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='repos.repository'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['user', '-created_at'], name='repos_repos_user_id_a839ee_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['visibility'], name='repos_repos_visibil_37b91c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='repofile',
            index=models.Index(fields=['repo'], name='repos_repof_repo_id_3cdf04_idx'),
        ),
    ]
