# Generated by Django 4.2.30 on 2026-05-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='languages',
            field=models.CharField(blank=True, help_text='Comma separated languages', max_length=255, null=True),
        ),
    ]
